import Head from "next/head";
import ky from "ky-universal";
import { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from "next";
import { Card } from "../../card.model";
import { Set } from "../../set.model";

import Footer from "../../components/Footer";
import CardsApp from "../../components/CardsApp";
import Navbar from "../../components/Navbar";

export default function CardsPage({
  playedCardsData,
  allCardsData,
  set,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const setName = set.data[0].name;
  return (
    <div className="antialiased">
      <Head>
        <title>{setName} | Alphdex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="my-20 space-y-10 overflow-hidden">
        <h1 className="font-extrabold text-4xl text-center">{setName}</h1>
        <CardsApp
          playedCards={playedCardsData.results}
          allCards={allCardsData.data}
        />
      </div>
      <Footer />
    </div>
  );
}

export const getStaticPaths: GetStaticPaths = async () => {
  // When this is true (in preview environments) don't
  // prerender any static pages
  // (faster builds, but slower initial page load)
  if (process.env.SKIP_BUILD_STATIC_GENERATION) {
    return {
      paths: [],
      fallback: "blocking",
    };
  }

  const APIRes = await ky(`https://api.pokemontcg.io/v2/sets?select=id,name`);
  let APISetsData: any = await APIRes.json();

  const paths = APISetsData.data.map(async (set: Set) => {
    let res = await ky(
      `${process.env.NEXT_PUBLIC_HOST}/api/sets/?code=${set.id}`
    );
    let localSetData: any = await res.json();
    return {
      params: { slug: localSetData.results[0].slug },
    };
  });

  // { fallback: false } means other routes should 404
  return { paths, fallback: false };
};

export const getStaticProps: GetStaticProps = async (context: any) => {
  const setIdRegex = /\w+$/g;
  const setId = context.params.slug.match(setIdRegex);

  let res = await ky(
    `${process.env.NEXT_PUBLIC_HOST}/api/cards/?set__code=${setId}`
  );
  const playedCardsData: Card[] = await res.json();
  res = await ky(
    `https://api.pokemontcg.io/v2/cards?q=set.id:"${setId}"&select=name,number,images,set`
  );
  const allCardsData: any = await res.json();
  for (
    let i = 2;
    allCardsData.totalCount > allCardsData.pageSize;
    i++, allCardsData.totalCount -= allCardsData.pageSize
  ) {
    res = await ky(
      `https://api.pokemontcg.io/v2/cards?q=set.id:"${setId}"&select=name,number,images,set&page=${i}`
    );
    const cardData: any = await res.json();
    allCardsData.data.push(...cardData.data);
  }
  const set = await ky(
    `https://api.pokemontcg.io/v2/sets?q=id:"${setId}"&select=name`
  ).json();
  return {
    props: {
      playedCardsData,
      allCardsData,
      set,
    },
  };
};
