import Head from "next/head";
import ky from "ky-universal";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { Card } from "../card.model";
import Header from "../components/Header";
import Footer from "../components/Footer";
import CardsApp from "../components/CardsApp";

export default function Home({
  playedCards,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(typeof playedCards);
  return (
    <div>
      <Head>
        <title>Alphdex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <CardsApp playedCards={playedCards} />
      <Footer />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await ky.get(`${process.env.NEXT_PUBLIC_HOST}/api/cards/`);
  const playedCards: Card[] = await res.json();
  return {
    props: {
      playedCards,
    },
  };
};
