import Head from "next/head";
import ky from "ky-universal";
import { GetStaticProps } from "next";
import { Card } from "../card.model";
import Header from "../components/Header";
import Footer from "../components/Footer";
import CardsApp from "../components/CardsApp";

export default function Home({ playedCardsData }: { playedCardsData: Card[] }) {
  return (
    <div>
      <Head>
        <title>Alphdex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <CardsApp playedCards={playedCardsData} />
      <Footer />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  let playedCardsData;
  try {
    playedCardsData = await ky
      .get(`${process.env.NEXT_PUBLIC_HOST}/api/cards/`)
      .json();
  } catch (err) {
    console.log(`API Error: ${err}`);
  }
  return {
    props: {
      playedCardsData,
    },
  };
};
