import SetsApp from "../components/SetsApp";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { Set } from "../set.model";
import ky from "ky-universal";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

export default function Sets({
  setsData,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div className="antialiased text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900">
      <Head>
        <title>Sets | Alphdex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight dark:text-slate-200 text-center">
        Sets
      </h1>
      <div className="flex justify-center">
        <SetsApp sets={setsData.data.reverse()} />
      </div>
      <Footer />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await ky(
    `https://api.pokemontcg.io/v2/sets?select=id,name,images`
  );
  const setsData: Set[] = await res.json();
  return {
    props: {
      setsData,
    },
  };
};
