import Head from "next/head";
import ky from "ky-universal";
import { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from "next";
import { Card } from "../../card.model";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import Navbar from "../../components/Navbar";
import CardApp from "../../components/CardApp";

export default function CardsPage({
  playedCardsData,
  allCardsData,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div>
      <Head>
        <title>Card | Alphdex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <CardApp />
      <Footer />
    </div>
  );
}

export const getStaticPaths: GetStaticPaths = async () => {
  // When this is true (in preview environments) don't
  // prerender any static pages
  // (faster builds, but slower initial page load)
  if (process.env.SKIP_BUILD_STATIC_GENERATION) {
    return {
      paths: [],
      fallback: "blocking",
    };
  }

  const res = await ky(
    `https://api.pokemontcg.io/v2/cards?select=name,number,set&q=name:${cardName} number:${number} set.id:${setId}`
  );
  const cardData: any = await res.json();
  const card: Card[] = cardData.data;

  const paths = card.map((card: Card) => ({
    params: { id: card.id },
  }));

  // { fallback: false } means other routes should 404
  return { paths, fallback: false };
};

export const getStaticProps: GetStaticProps = async (context: any) => {
  let res = await ky(
    `${process.env.NEXT_PUBLIC_HOST}/api/cards/?set__code=${context.params.id}`
  );
  const playedCardsData: Card[] = await res.json();
  res = await ky(
    `https://api.pokemontcg.io/v2/cards?q=set.id:"${context.params.id}"&select=name,number,images,set`
  );
  const allCardsData: Card[] = await res.json();
  return {
    props: {
      playedCardsData,
      allCardsData,
    },
  };
};
