# Generated by Django 3.2.15 on 2022-11-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20220921_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['set', 'number']},
        ),
    ]
